stages:
  - test
  - deploy

pages:
  image:
    name: cirocosta/alpine-envsubst:latest
    entrypoint: [ "" ]
  variables:
    DOCSIFY_BASE_PATH: https://thaikolja.gitlab.io/-/secondary-title/docs
    docsify: $docsify
  stage: deploy
  script:
    - mkdir .public
    - mv index.html .index.html
    - envsubst < ".index.html" > "index.html"
    - rm -f .index.html
    - cp -r * .public
    - mv .public public
    - ls
  artifacts:
    paths:
      - public
  only:
    - master
